import React, { useState, useEffect, useRef } from 'react';
import { Send, Bot, User, RefreshCw, Sparkles, Tag } from 'lucide-react';
import { BotConfig, Message } from '../types';
import { sendChatMessage } from '../services/geminiService';

interface ChatPreviewProps {
  config: BotConfig;
}

const ChatPreview: React.FC<ChatPreviewProps> = ({ config }) => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  // Reset chat when config changes (optional, but good for Preview feel)
  useEffect(() => {
    if (messages.length === 0 && config.welcomeMessage) {
       setMessages([{
        id: 'welcome',
        role: 'model',
        text: config.welcomeMessage,
        timestamp: Date.now()
      }]);
    }
  }, [config.welcomeMessage]);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSend = async (textOverride?: string) => {
    const textToSend = textOverride || input;
    if (!textToSend.trim() || loading) return;

    const userMsg: Message = {
      id: Date.now().toString(),
      role: 'user',
      text: textToSend,
      timestamp: Date.now()
    };

    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setLoading(true);

    try {
      // Filter out the welcome message for the API call history if needed, 
      // usually welcome message is not part of conversation history for the LLM context unless generated by it.
      // We'll just pass the user history.
      const history = messages.filter(m => m.id !== 'welcome');
      
      const responseText = await sendChatMessage(history, userMsg.text, config.systemInstruction);
      
      const botMsg: Message = {
        id: (Date.now() + 1).toString(),
        role: 'model',
        text: responseText,
        timestamp: Date.now()
      };
      setMessages(prev => [...prev, botMsg]);
    } catch (err) {
      // Error handled in service, but we can show a UI error here
    } finally {
      setLoading(false);
    }
  };

  const handleRestart = () => {
    setMessages([{
      id: 'welcome',
      role: 'model',
      text: config.welcomeMessage,
      timestamp: Date.now()
    }]);
  };

  return (
    <div className="bg-white dark:bg-gray-800 rounded-[2rem] shadow-2xl border border-gray-200 dark:border-gray-700 overflow-hidden flex flex-col h-[600px] w-full max-w-sm mx-auto relative transition-colors duration-300">
      {/* Header */}
      <div 
        className="p-4 flex items-center justify-between text-white"
        style={{ backgroundColor: config.primaryColor }}
      >
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center backdrop-blur-sm overflow-hidden">
             <img src={config.logoUrl} alt="Bot" className="w-full h-full object-cover" />
          </div>
          <div>
            <h3 className="font-bold text-sm">{config.name}</h3>
            <p className="text-xs text-white/80 flex items-center gap-1">
              <span className={`w-1.5 h-1.5 rounded-full ${config.isActive !== false ? 'bg-green-400 animate-pulse' : 'bg-red-400'}`}></span>
              {config.isActive !== false ? 'آنلاین' : 'آفلاین'}
            </p>
          </div>
        </div>
        <button onClick={handleRestart} className="p-2 hover:bg-white/10 rounded-full transition-colors" title="شروع مجدد">
          <RefreshCw size={18} />
        </button>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-gray-50" ref={scrollRef}>
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`flex items-end gap-2 ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}
          >
            <div className={`w-8 h-8 rounded-full flex-shrink-0 flex items-center justify-center text-white text-xs
              ${msg.role === 'user' ? 'bg-gray-400' : ''}`}
              style={msg.role === 'model' ? { backgroundColor: config.primaryColor } : {}}
            >
              {msg.role === 'user' ? <User size={14} /> : <Bot size={14} />}
            </div>
            <div
              className={`max-w-[80%] p-3 rounded-2xl text-sm leading-relaxed shadow-sm
                ${msg.role === 'user' 
                  ? 'bg-white text-gray-800 rounded-bl-none border border-gray-100' 
                  : 'text-white rounded-br-none'
                }`}
              style={msg.role === 'model' ? { backgroundColor: config.primaryColor } : {}}
            >
              {msg.text}
            </div>
          </div>
        ))}
        {loading && (
          <div className="flex items-end gap-2">
             <div className="w-8 h-8 rounded-full flex-shrink-0 flex items-center justify-center text-white text-xs"
                  style={{ backgroundColor: config.primaryColor }}>
                <Bot size={14} />
             </div>
             <div className="bg-white border border-gray-100 p-3 rounded-2xl rounded-br-none shadow-sm">
               <div className="flex gap-1">
                 <span className="w-2 h-2 bg-gray-300 rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></span>
                 <span className="w-2 h-2 bg-gray-300 rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></span>
                 <span className="w-2 h-2 bg-gray-300 rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></span>
               </div>
             </div>
          </div>
        )}
      </div>

      {/* Suggestion Chips & Input */}
      <div className="bg-white border-t border-gray-100">
        
        {/* Suggestions */}
        {config.suggestions && config.suggestions.length > 0 && (
           <div className="px-4 pt-2 flex gap-2 overflow-x-auto pb-1 no-scrollbar">
              {config.suggestions.map((suggestion, idx) => (
                  <button
                     key={idx}
                     onClick={() => handleSend(suggestion)}
                     disabled={loading}
                     className="flex-shrink-0 text-xs bg-gray-100 hover:bg-gray-200 text-gray-700 px-3 py-1.5 rounded-full transition-colors border border-gray-200 whitespace-nowrap"
                  >
                      {suggestion}
                  </button>
              ))}
           </div>
        )}

        {/* Input Area */}
        <div className="p-4">
            <div className="relative flex items-center">
            <input
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSend()}
                placeholder={config.chatInputPlaceholder || "پیام خود را بنویسید..."}
                className="w-full bg-gray-50 border border-gray-200 rounded-full py-3 pr-4 pl-12 text-sm focus:outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100 transition-all text-gray-800"
            />
            <button 
                onClick={() => handleSend()}
                disabled={!input.trim() || loading}
                className="absolute left-2 top-1/2 -translate-y-1/2 p-2 bg-blue-600 text-white rounded-full hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-md shadow-blue-600/20"
            >
                <Send size={16} className={loading ? 'opacity-0' : 'rtl:rotate-180'} />
                {loading && <Sparkles size={16} className="absolute top-2 left-2 animate-spin" />}
            </button>
            </div>
            <div className="text-center mt-2">
                <span className="text-[10px] text-gray-400">قدرت گرفته از N8N و Gemini</span>
            </div>
        </div>
      </div>
    </div>
  );
};

export default ChatPreview;